### ISSUE TITLE
Move Linkage Monitor CI to use Bazel to cache the result

### ISSUE THREAD

**Issue by suztomo** [protocolbuffers/protobuf#12912]
(I'm going to work on this)

**What language does this apply to?**
Java build

**Describe the problem you are trying to solve.**

Linkage Monitor check https://github.com/protocolbuffers/protobuf/blob/main/.github/workflows/test_java.yml#L50 is slow even when there's no change.

**Describe the solution you'd like**

Create Bazel test rule that only runs when there's change in Protobuf Java code.

**Describe alternatives you've considered**

**Additional context**

Email thread "Shall we replace Linkage Monitor check with a check leveraging Showcase API?". Mike shared an idea to run it in Bazel so that the Linkage Monitor only runs when there's a change in Java code. I'm going to work on it.

Previously we assessed the alternative to Linkage Monitor but we didn't find one. https://github.com/protocolbuffers/protobuf/issues/8977

# Resources

https://bazel.build/rules/testing#using-test-target

```
  linkage-monitor:
    name: Linux Linkage Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pending changes
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ inputs.safe-checkout }}
      - name: Build protoc
        id: build-protoc
        uses: protocolbuffers/protobuf-ci/cross-compile-protoc@v1
        with:
          image: us-docker.pkg.dev/protobuf-build/containers/common/linux/bazel:5.1.1-6361b3a6e5c97e9951d03a4de28542fc45f1adab
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          architecture: linux-x86_64
      - name: Move protoc into place and clean up
        run: |
          mv ${{ steps.build-protoc.outputs.protoc }} protoc
          sudo rm -rf _build
      - name: Install snapshot version locally
        run: |
          cd java
          mvn -e -B -Dhttps.protocols=TLSv1.2 install -Dmaven.test.skip=true
      - name: Download Linkage Monitor
        run: curl -v -O "https://storage.googleapis.com/cloud-opensource-java-linkage-monitor/linkage-monitor-latest-all-deps.jar"
      - name: Fails if there's new linkage errors compared with baseline
        run: java -Xmx2048m -jar linkage-monitor-latest-all-deps.jar com.google.cloud:libraries-bom
```

# Consideration

- Linkage Monitor uses the latest version of the Libraries BOM. The test is not exactly reproducible.
- The protoc generation step "build-protoc" seems unnecessary as long as Maven command can find protoc from Bazel target output
- mvn cannot work in Bazel's sandbox environment? I got `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project protobuf-bom: Failed to install artifact com.google.protobuf:protobuf-bom:pom:3.23.0: /Users/suztomo/.m2/repository/com/google/protobuf/protobuf-bom/3.23.0/protobuf-bom-3.23.0.pom (Operation not permitted)`
