### ISSUE TITLE
Configure test for support of 8-byte atomics does not add `-latomic` flag when needed

### ISSUE THREAD

**Issue by barracuda156** [protocolbuffers/protobuf#21814]
**What version of protobuf and what language are you using?**
v. 30.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 14.2.0

**What did you do?**
Run the build on 32-bit powerpc (or perhaps arm or mips), see that linking fails.

**What did you expect to see**
`-latomic` should be passed to the linker.

**What did you see instead?**
The build ignored result of configure test and did nothing.

Configure test (correctly failing)
```
    kind: "try_compile-v1"
    backtrace:
      - "/opt/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/opt/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "CMakeLists.txt:190 (check_cxx_source_compiles)"
    checks:
      - "Performing Test protobuf_HAVE_BUILTIN_ATOMICS"
    directories:
      source: "/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build/CMakeFiles/CMakeScratch/TryCompile-ANM3ux"
      binary: "/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build/CMakeFiles/CMakeScratch/TryCompile-ANM3ux"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "-pipe -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0"
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport"
      CMAKE_MODULE_PATH: "/opt/local/share/cmake/Modules"
      CMAKE_OSX_ARCHITECTURES: "ppc"
      CMAKE_OSX_DEPLOYMENT_TARGET: "10.6"
      CMAKE_OSX_SYSROOT: "/"
      CMAKE_POSITION_INDEPENDENT_CODE: "ON"
      CMAKE_WARN_DEPRECATED: "FALSE"
    buildResult:
      variable: "protobuf_HAVE_BUILTIN_ATOMICS"
      cached: true
      stdout: |
        Change Dir: '/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build/CMakeFiles/CMakeScratch/TryCompile-ANM3ux'
       
        Run Build Command(s): /opt/local/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_1f62b/fast
        /usr/bin/make  -f CMakeFiles/cmTC_1f62b.dir/build.make CMakeFiles/cmTC_1f62b.dir/build
        make[1]: Entering directory `/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build/CMakeFiles/CMakeScratch/TryCompile-ANM3ux'
        Building CXX object CMakeFiles/cmTC_1f62b.dir/src.cxx.o
        /opt/local/bin/g++-mp-14 -Dprotobuf_HAVE_BUILTIN_ATOMICS  -pipe -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 -arch ppc -mmacosx-version-min=10.6 -fPIE -o CMakeFiles/cmTC_1f62b.dir/src.cxx.o -c /opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build/CMakeFiles/CMakeScratch/TryCompile-ANM3ux/src.cxx
        Linking CXX executable cmTC_1f62b
        /opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1f62b.dir/link.txt --verbose=1
        Undefined symbols for architecture ppc:
          "___atomic_load_8", referenced from:
              std::__atomic_base<long long>::operator long long() const in src.cxx.o
        ld: symbol(s) not found for architecture ppc
        collect2: error: ld returned 1 exit status
        /opt/local/bin/g++-mp-14 -pipe -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 -arch ppc -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport  CMakeFiles/cmTC_1f62b.dir/src.cxx.o -o cmTC_1f62b
        make[1]: *** [cmTC_1f62b] Error 1
        make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build/CMakeFiles/CMakeScratch/TryCompile-ANM3ux'
        make: *** [cmTC_1f62b/fast] Error 2
       
      exitCode: 2
```

But then its result is left unused, and the build fails:
```
[ 35%] Building CXX object CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format_lite.cc.o
/opt/local/bin/g++-mp-14 -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_ZLIB -DLIBPROTOBUF_EXPORTS -DPROTOBUF_USE_DLLS -Dlibprotobuf_EXPORTS -I/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build -I/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/protobuf-30.2 -I/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/build/src -I/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/protobuf-30.2/src -I/opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/protobuf-30.2/third_party/utf8_range -isystem /opt/local/include -pipe -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -O2 -g -DNDEBUG -arch ppc -mmacosx-version-min=10.6 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format_lite.cc.o -MF CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format_lite.cc.o.d -o CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format_lite.cc.o -c /opt/local/var/macports/build/_opt_local_ppcports_devel_protobuf/protobuf/work/protobuf-30.2/src/google/protobuf/wire_format_lite.cc
[ 35%] Linking CXX executable protoc-gen-upb
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/protoc-gen-upb.dir/link.txt --verbose=ON
Undefined symbols for architecture ppc:
  "___atomic_fetch_add_8", referenced from:
      google::protobuf::internal::ThreadSafeArena::GetNextLifeCycleId() in arena.cc.o
      google::protobuf::TextFormat::Printer::TryRedactFieldValue(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*, google::protobuf::TextFormat::BaseTextGenerator*, bool) const in text_format.cc.o
  "___atomic_load_8", referenced from:
      google::protobuf::internal::GetRedactedFieldCount() in text_format.cc.o
ld: symbol(s) not found for architecture ppc
collect2: error: ld returned 1 exit status
/opt/local/bin/g++-mp-14 -pipe -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -O2 -g -DNDEBUG -arch ppc -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/any.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/any_lite.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/arena.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/arena_align.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/arenastring.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/arenaz_sampler.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/compiler/code_generator.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/compiler/code_generator_lite.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/compiler/plugin.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/compiler/plugin.pb.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/compiler/retention.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/cpp_features.pb.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/descriptor.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/descriptor.pb.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/descriptor_database.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/dynamic_message.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/extension_set.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/extension_set_heavy.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/feature_resolver.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/generated_enum_util.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/generated_message_bases.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/generated_message_reflection.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/generated_message_tctable_full.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/generated_message_tctable_gen.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/generated_message_tctable_lite.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/generated_message_util.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/implicit_weak_message.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/inlined_string_field.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/coded_stream.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/gzip_stream.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/io_win32.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/printer.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/strtod.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/tokenizer.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/zero_copy_sink.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/zero_copy_stream.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/zero_copy_stream_impl.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/io/zero_copy_stream_impl_lite.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/map.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/map_field.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/message.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/message_lite.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/parse_context.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/port.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/raw_ptr.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/reflection_mode.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/reflection_ops.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/repeated_field.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/repeated_ptr_field.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/service.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/stubs/common.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/text_format.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/unknown_field_set.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/wire_format.cc.o" "CMakeFiles/protoc-gen-upb.dir/src/google/protobuf/wire_format_lite.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/c/generator.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/c/names.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/c/names_internal.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/common.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/common/names.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/file_layout.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/minitable/names.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/minitable/names_internal.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/plugin.cc.o" "CMakeFiles/protoc-gen-upb.dir/upb_generator/cmake/google/protobuf/compiler/plugin.upb_minitable.c.o" -o protoc-gen-upb-30.2.0  -Wl,-rpath,@loader_path/../lib third_party/utf8_range/libutf8_validity.30.2.0.dylib libupb.a /opt/local/lib/libabsl_die_if_null.2505.0.0.dylib /opt/local/lib/libabsl_log_initialize.2505.0.0.dylib /opt/local/lib/libabsl_statusor.2505.0.0.dylib third_party/utf8_range/libutf8_range.30.2.0.dylib /opt/local/lib/libabsl_log_internal_check_op.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_conditions.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_message.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_nullguard.2505.0.0.dylib /opt/local/lib/libabsl_examine_stack.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_format.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_structured_proto.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_proto.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_log_sink_set.2505.0.0.dylib /opt/local/lib/libabsl_log_sink.2505.0.0.dylib /opt/local/lib/libabsl_flags_internal.2505.0.0.dylib /opt/local/lib/libabsl_flags_marshalling.2505.0.0.dylib /opt/local/lib/libabsl_flags_reflection.2505.0.0.dylib /opt/local/lib/libabsl_flags_config.2505.0.0.dylib /opt/local/lib/libabsl_flags_program_name.2505.0.0.dylib /opt/local/lib/libabsl_flags_private_handle_accessor.2505.0.0.dylib /opt/local/lib/libabsl_flags_commandlineflag.2505.0.0.dylib /opt/local/lib/libabsl_flags_commandlineflag_internal.2505.0.0.dylib /opt/local/lib/libabsl_log_globals.2505.0.0.dylib /opt/local/lib/libabsl_vlog_config_internal.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_fnmatch.2505.0.0.dylib /opt/local/lib/libabsl_log_internal_globals.2505.0.0.dylib /opt/local/lib/libabsl_raw_hash_set.2505.0.0.dylib /opt/local/lib/libabsl_hash.2505.0.0.dylib /opt/local/lib/libabsl_city.2505.0.0.dylib /opt/local/lib/libabsl_low_level_hash.2505.0.0.dylib /opt/local/lib/libabsl_hashtablez_sampler.2505.0.0.dylib /opt/local/lib/libabsl_random_distributions.2505.0.0.dylib /opt/local/lib/libabsl_random_seed_sequences.2505.0.0.dylib /opt/local/lib/libabsl_random_internal_entropy_pool.2505.0.0.dylib /opt/local/lib/libabsl_random_internal_randen.2505.0.0.dylib /opt/local/lib/libabsl_random_internal_randen_hwaes.2505.0.0.dylib /opt/local/lib/libabsl_random_internal_randen_hwaes_impl.2505.0.0.dylib /opt/local/lib/libabsl_random_internal_randen_slow.2505.0.0.dylib /opt/local/lib/libabsl_random_internal_platform.2505.0.0.dylib /opt/local/lib/libabsl_random_internal_seed_material.2505.0.0.dylib /opt/local/lib/libabsl_random_seed_gen_exception.2505.0.0.dylib /opt/local/lib/libabsl_status.2505.0.0.dylib /opt/local/lib/libabsl_cord.2505.0.0.dylib /opt/local/lib/libabsl_cordz_info.2505.0.0.dylib /opt/local/lib/libabsl_cord_internal.2505.0.0.dylib /opt/local/lib/libabsl_cordz_functions.2505.0.0.dylib /opt/local/lib/libabsl_exponential_biased.2505.0.0.dylib /opt/local/lib/libabsl_cordz_handle.2505.0.0.dylib /opt/local/lib/libabsl_synchronization.2505.0.0.dylib /opt/local/lib/libabsl_graphcycles_internal.2505.0.0.dylib /opt/local/lib/libabsl_kernel_timeout_internal.2505.0.0.dylib /opt/local/lib/libabsl_time.2505.0.0.dylib /opt/local/lib/libabsl_civil_time.2505.0.0.dylib /opt/local/lib/libabsl_time_zone.2505.0.0.dylib -Wl,-framework,CoreFoundation /opt/local/lib/libabsl_tracing_internal.2505.0.0.dylib /opt/local/lib/libabsl_crc_cord_state.2505.0.0.dylib /opt/local/lib/libabsl_crc32c.2505.0.0.dylib /opt/local/lib/libabsl_crc_internal.2505.0.0.dylib /opt/local/lib/libabsl_crc_cpu_detect.2505.0.0.dylib /opt/local/lib/libabsl_stacktrace.2505.0.0.dylib /opt/local/lib/libabsl_leak_check.2505.0.0.dylib /opt/local/lib/libabsl_strerror.2505.0.0.dylib /opt/local/lib/libabsl_symbolize.2505.0.0.dylib /opt/local/lib/libabsl_debugging_internal.2505.0.0.dylib /opt/local/lib/libabsl_malloc_internal.2505.0.0.dylib /opt/local/lib/libabsl_demangle_internal.2505.0.0.dylib /opt/local/lib/libabsl_demangle_rust.2505.0.0.dylib /opt/local/lib/libabsl_decode_rust_punycode.2505.0.0.dylib /opt/local/lib/libabsl_utf8_for_code_point.2505.0.0.dylib /opt/local/lib/libabsl_str_format_internal.2505.0.0.dylib /opt/local/lib/libabsl_strings.2505.0.0.dylib /opt/local/lib/libabsl_string_view.2505.0.0.dylib /opt/local/lib/libabsl_throw_delegate.2505.0.0.dylib /opt/local/lib/libabsl_int128.2505.0.0.dylib /opt/local/lib/libabsl_strings_internal.2505.0.0.dylib /opt/local/lib/libabsl_base.2505.0.0.dylib /opt/local/lib/libabsl_raw_logging_internal.2505.0.0.dylib /opt/local/lib/libabsl_log_severity.2505.0.0.dylib /opt/local/lib/libabsl_spinlock_wait.2505.0.0.dylib
make[2]: *** [protoc-gen-upb-30.2.0] Error 1
```
